### PR TITLE
if you don't have a private key, show a message

### PR DESCRIPTION
**Pull request by AlexMunoz**
if you don't have a private key, the list is empty. It should give you a message.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/muelli/geysigning/pull/41" target="_blank">ReviewNinja

**Comment by AlexMunoz** [comment]
not yet :/, but we will need to make translatable strings.

**Comment by muelli** [comment]
On Thu, Mar 19, 2015 at 07:48:30AM -0700, Alex Munoz wrote:
> not yet :/, but we will need to make translatable strings.
Heh. So when we apply the patch the code will break? ;-)

**Comment by AlexMunoz** [comment]
Nein, but I've updated the patch. ;-)

**Comment by muelli** [comment]
The patch is good. I'd like to have something more useful, though.  Maybe we can make it show smth like "please run gpg --gen-key" or so. But it's a touchy subject. Maybe we can call seahorse in a way such that it will create a key.
Let me know if you have ideas.
I'll merge that soon, anyway.

**Comment by muelli** [comment]
I've merged this functionality \o/ Thanks!

**Pull request closed without merging**
