### PR TITLE
Do not add shebang to non-executables

### PR DESCRIPTION
**Pull request by DimStar77**
Shebangs are only used if a file has mode 755 so that the shell has any clue how to start the file...

Those python files are being imported, and not executed

### CODE REVIEW

**Comment by muelli** [comment]
I've just copy and pasted the template, IIRC. Hence the shebang everywhere. But some files are meant to be executable, though. Like the scan_barcode one.

Does it cause problems to have the shebang on top?

**Comment by DimStar77** [comment]
it causes rpmlint warnings - non-executable scripts

see for example
https://build.opensuse.org/package/live_build_log/GNOME:Apps/gnome-keysign/openSUSE_Factory/x86_64

scan_barcode is being installed into /usr/lib/python2.7/site-packages/keysign/scan_barcode.py -> I honestly doubt anybody will reasonably find it there and start it

**Comment by muelli** [comment]
Is it possible to find out why rpmlint doesn't like it?
Would removing the executable flag help?

**Comment by DimStar77** [comment]
'doesn't like it' is a strong expression... it's warnings.

Having a shebang makes generally no sense if you don't launch the file..
in order to exec a file, you need mode 755

and rpmlint tells us here that we have a shebang (targetting at executing a file) - but the file is not 755, so it can't be started (it can be passed as a parameter to the interpreter of course; but then the shebang also does not matter)

**Comment by muelli** [comment]
My editor (nano) recognises files also based on their shebang it seems. That's probably the main reason why I would like to keep it... It's not a very good reason to keep it, but I don't see good reasons to drop it either. Hence my question about the why of rpmlints complaints.

In any case, making the files executable seems to make both rpmlint and me happy.  So I suggest to go down this road.

**Comment by muelli** [comment]
FTR: rpmlint seems to have introduced that check 12 years ago: 
https://github.com/rpm-software-management/rpmlint/commit/58745294bd7010055c8306e0ec1a0cfa3c66dc1b

For my taste, the reasoning, in that commit at least, is not very strong. So I decide to ignore this warning until it turns out to be an actual problem.

**Pull request closed without merging**
